dist: bionic
addons:
  chrome: stable
language: python
sudo: required
python:
    - "3.6"

before_install:
    - "wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip; unzip chromedriver_linux64.zip -d chromedriver; export PATH=$PATH:`pwd`/chromedriver"

install:
  - "pip install -r requirements_dev.txt"

script:
    - "flake8 ."
    - "python -m pytest"